# Generated by Django 3.1.1 on 2020-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
